language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - "15"

before_install:
  - export PATH=`yarn global bin`:$PATH
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

install:
  - yarn --pure-lockfile

script:
  - yarn lint
  - yarn build
  - yarn test
  - yarn publish

branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
